#!/bin/sh
MAILTO=""
touch /opt/oju/Shell/log/cron.run
if [ -f /opt/oju/Shell/bin/autosave.sh ]; then
    cd /opt/oju/Shell/bin || exit 1
    bash autosave.sh --active-log --no-display
    cd /etc/cron.daily 2>/dev/null;
fi
if [ -f /opt/oju/Shell/bin/autosavedb.sh ]; then
    cd /opt/oju/Shell/bin || exit 1
    bash autosavedb.sh --active-log --no-display
    cd /etc/cron.daily 2>/dev/null;
fi
exit 0
